### ISSUE TITLE
  Type 'Promise<void>' is not assignable to type 'void | UnsubscribeFn | Subscription<any>'.

### ISSUE THREAD

**Issue by patarapolw** [andywer/observable-fns#12]
Is this by design?

So, in TypeScript, I cannot use

```ts
new Observable(async (obs) => {})
```

Instead, I have to,

```ts
new Observable(obs => {
  (async () => {})().catch(obs.error)
})
```

**Comment by andywer** [comment]
You don't return an unsubscribe function? I think that's why I never ran into that…

But yeah, we can fix that 👍

**Comment by andywer** [comment]
Ohh, wait. The issue is actually more related to the fact that the initialization function is async. That's a bit strange. You should not have an async initialization function as you can never return an unsubscribe function this way…

Makes sense?

**Comment by patarapolw** [comment]
Just like `Class constructor` should never be async, `initialization` might should never be async nor blocking as well.

> You should not have an async initialization function as you can never return an unsubscribe function this way

I still don't really get it. But it isn't mention in the tutorial -- https://rxjs-dev.firebaseapp.com/guide/observable

Also, onError might also be

```ts
new Observable(obs => {
  (async () => {})().catch((e) => {
    obs.error(e)
    obs.complete()
  })
})
```

**Comment by andywer** [comment]
The unsubscribe function (if you have any – and usually you should have one) must be returned synchronously, that's why an async initialization function is a problem.

I was once thinking the same regarding `obs.error()` + `obs.complete()`, but then realized that an observable only fails once – it auto-closes on failure. So you don't need to explicitly `obs.complete()`. `obs.error()` already closes the observable 😉

**Comment by patarapolw** [comment]
I think I start to get what you meant on [dev.to](https://dev.to/andywer/comment/p4j5).
